# Generated by Django 3.1 on 2020-08-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howailapp', '0002_auto_20200810_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstype',
            name='bizdesc',
        ),
    ]
