# Generated by Django 3.1 on 2020-08-10 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('howailapp', '0003_remove_businesstype_bizdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTypeDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bizdivname', models.CharField(max_length=200)),
                ('bizdivactivity', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('businesstype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howailapp.businesstype')),
            ],
            options={
                'ordering': ['bizdivname'],
            },
        ),
    ]
