# Generated by Django 3.1 on 2020-08-10 11:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('howailapp', '0004_businesstypedivision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstype',
            options={'ordering': ['biztype']},
        ),
        migrations.CreateModel(
            name='DivisionProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producttype', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('businesstypedivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howailapp.businesstypedivision')),
            ],
            options={
                'ordering': ['producttype'],
            },
        ),
    ]
