# Generated by Django 3.1 on 2020-08-10 11:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('howailapp', '0005_auto_20200810_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionProductSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsize', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('divisionproducttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howailapp.divisionproducttype')),
            ],
            options={
                'ordering': ['productsize'],
            },
        ),
    ]
