# Generated by Django 3.1 on 2020-08-10 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('howailapp', '0008_auto_20200810_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('divisionproductpattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howailapp.divisionproductpattern')),
                ('divisionproductsizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howailapp.divisionproductsizes')),
            ],
            options={
                'ordering': ['divisionproductsizes'],
            },
        ),
    ]
