# Generated by Django 3.1 on 2020-08-11 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('howailapp', '0009_divisionproductlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('faxno', models.CharField(max_length=100)),
                ('telno', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Business Sector',
                'verbose_name_plural': 'Business Sectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('faxno', models.CharField(max_length=100)),
                ('telno', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howailapp.businessactivity')),
            ],
            options={
                'verbose_name': 'Business Division',
                'verbose_name_plural': 'Business Divisions',
                'ordering': ['division'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('faxno', models.CharField(max_length=100)),
                ('telno', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='businesstypedivision',
            name='businesstype',
        ),
        migrations.RemoveField(
            model_name='divisionproductlist',
            name='divisionproductpattern',
        ),
        migrations.RemoveField(
            model_name='divisionproductlist',
            name='divisionproductsizes',
        ),
        migrations.RemoveField(
            model_name='divisionproductpattern',
            name='divisionproducttype',
        ),
        migrations.RemoveField(
            model_name='divisionproductsizes',
            name='divisionproducttype',
        ),
        migrations.RemoveField(
            model_name='divisionproducttype',
            name='businesstypedivision',
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
        migrations.DeleteModel(
            name='BusinessTypeDivision',
        ),
        migrations.DeleteModel(
            name='DivisionProductList',
        ),
        migrations.DeleteModel(
            name='DivisionProductPattern',
        ),
        migrations.DeleteModel(
            name='DivisionProductSizes',
        ),
        migrations.DeleteModel(
            name='DivisionProductType',
        ),
        migrations.AddField(
            model_name='businessdivision',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howailapp.organization'),
        ),
        migrations.AddField(
            model_name='businessactivity',
            name='division',
            field=models.ManyToManyField(to='howailapp.BusinessDivision'),
        ),
        migrations.AddField(
            model_name='businessactivity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howailapp.organization'),
        ),
    ]
