# Generated by Django 3.1 on 2020-08-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howailapp', '0010_auto_20200811_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdivision',
            name='activity',
        ),
    ]
