# Generated by Django 3.1 on 2020-08-11 18:37

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('howailapp', '0011_remove_businessdivision_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage('C:\\Users\\Raffy\\Documents\\AlHowailGroup\\static', 'pattern'), upload_to='pattern')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howailapp.organization')),
            ],
            options={
                'verbose_name': 'Product Design',
                'verbose_name_plural': 'Product Designs',
                'ordering': ['design'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howailapp.organization')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='businessdivision',
            name='productcategory',
            field=models.ManyToManyField(to='howailapp.ProductCategory'),
        ),
    ]
